### PR TITLE
Allow replacing stylesheet to preserve the cascade

### LINKED ISSUE #325: Final cascaded rule does not work, always override by last Media Query
I have the following styles:

```@media (min-width: 768px) {
  .container {
    width: 750px;
    background: green;
  }
}
@media (min-width: 992px) {
  .container {
    width: 970px;
    background: blue;
  }
}
@media (min-width: 1200px) {
  .container {
    width: 1170px;
    background: orange;
  }
}

/* master override */
.container {
	width: 992px;
	background: red;
	margin: auto;
}
```
For some reasons, I have to override the container rule at the end while preserve the previous media query. In IE8, the final override does not work, it will be override by the last Media Query rules, ie, in the above example, it is 1170px. While in other browsers mentioned below, the final override work as expected, ie 992px.
Current work around is using keyword "!important".

Tested in IE8, latest Chrome / Firefox / Opera and Safari 5 in Windows 8.1

### PR DESCRIPTION
**Pull request by henrahmagix**
> Usually this library will append media queries in separate `<style>` elements.
> However, doing this changes the cascade such that a media rule will be used over
> a non-media rule. This is because the media rule is removed from its position
> and appended after everything else. It is a common case that a non-media rule
> will override a media rule, so this inversion of the cascade makes it very
> difficult to style for all browsers using this polyfill.
> 
> Turn on this option by setting `window.RESPOND_REPLACE_STYLES = true` before
> sourcing this script. It will remove every stylesheet it finds and move all CSS
> into the `media="all"` stylesheet that is appended, minus the inactive media
> query rules and those of other media types, like print. The other types are
> appended in the usual manner.

@incuna/js Please review, ta! The files to review are `README.md` and `src/respond.js`; the two `*.src.js` files are autocompiled from `src/respond.js`.

This fixes https://github.com/scottjehl/Respond/issues/325

### CODE REVIEW

**Comment by wytrych** [comment]
So what is this, a fork you want to push back?

**Comment by henrahmagix** [comment]
Yes.

> This branch has conflicts that must be resolved

Darn, I forgot that I branched off `1.4.2`, not `master`. I found that `master` wasn't working. Now that I'm familiar with the code, I'll see if I can rebase this onto `master` and get it working.

**Comment by henrahmagix** [comment]
This pull-request is first for internal review, then when in `master` we can use it in projects and make a pull-request to the source repo.

**Comment by henrahmagix** [comment]
@wytrych Fixed, ready for review

**Comment by henrahmagix** [comment]
@wytrych I introduced two bugs in the rebase. They're fixed now.

I was sure I had tested it, but I must have not been using the rebased code when testing in a project.

**Comment by wytrych** [comment]
There's an awful lot of code here in a library I have no knowledge of :( I'm not sure I can spot anything useful, getting to know the code would take me a lot of time.

**Comment by henrahmagix** [comment]
I can explain it for you in person if that helps?

**Comment by wytrych** [comment]
That would basically mean running through the code, which still takes a lot of time

**Comment by henrahmagix** [comment]
It'll be 5 minutes of explanation of the gist and a bit of detail regarding the changes here, then another 5-10 of answering questions you have.

**Comment by wytrych** [comment]
ok after lunch?

**Comment by henrahmagix** [comment]
:+1:

**Comment by henrahmagix** [comment]
Thanks!

**Pull request merged**
